# Site settings
title:          Вектор. Управление активами
description:    "С 2003 года управляем активами на Московской бирже. Договорные отношения. Блог. Совместная работа."
baseurl:        "/"
url:            "https://vector-am.ru"

# Google Analytics
google_analytics: G-W9VH0D4BP1

# Author
author:
  name:         Qt
  url:          https://vector-am.ru
  email:        post@ragve.ru

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale
